version: "3.8"
services:   
  worker:
    build:
      context: ./worker
    container_name: worker
    networks:
      - web_net
    volumes:
      - ./cct/files:/app/files

networks:
    web_net:
        driver: bridge
