version: "3.8"
services: 
  conversion-tool-api:
    build: .
    container_name: conversion_tool_api_app
    networks:
      - web_net
    ports:
     - "9876:9876"
    depends_on: 
      - db
  db: 
    container_name: conversion_tool_pg_db
    environment: 
      POSTGRES_USER: admin_db
      POSTGRES_PASSWORD: admin_conversion_tool_db
      POSTGRES_DB: conversion_db
    image: "postgres:latest"
    networks:
      - web_net
    ports: 
      - "5432:5432"
    volumes: 
      - ${PWD}/postgres-data:/var/lib/postgresql/data

networks:
    web_net:
        driver: bridge

volumes: 
  pg-data: 
    driver: local